[build]
  command = "npm run build"
  publish = ".next"
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    buildCommand = "npm run build"
  [plugins.inputs.environment]
    NODE_VERSION = "14.x"
    NEXT_TELEMETRY_DISABLED = "1"
[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

